

#spring.application.name=seguimiento_egresado_backend
#spring.datasource.url=jdbc:postgresql://172.102.4.125:5432/seg_egresados
#spring.datasource.username=postgres
#spring.datasource.password=oracle

spring.application.name=seguimiento_egresado_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=5400

